# Generated by Django 6.0.4 on 2026-09-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cursos',
            field=models.ManyToManyField(related_name='professores', to='core.curso'),
        ),
    ]
