# Generated by Django 6.0.4 on 2026-09-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_professor_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
