# Generated by Django 6.0.4 on 2026-07-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='experimental',
            field=models.BooleanField(default=False),
        ),
    ]
