# Generated by Django 6.0.4 on 2026-08-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso_professor_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
        migrations.CreateModel(
            name='HorarioProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado')], max_length=3)),
                ('horario', models.TimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'unique_together': {('professor', 'dia_semana', 'horario')},
            },
        ),
        migrations.AlterField(
            model_name='aula',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horarioprofessor'),
        ),
    ]
